#!/usr/bin/env node
/* Deterministic pipeline health check. Run from project root: node scripts/health-check.js
 * Exit 0 = healthy (warnings allowed), 1 = failures present. No LLM self-reporting. */
const fs = require('fs'), path = require('path');
const R = (p) => { try { return fs.readFileSync(p, 'utf8'); } catch { return ''; } };
let fails = 0, warns = 0;
const ok = (m) => console.log('  PASS ' + m);
const warn = (m) => { warns++; console.log('  WARN ' + m); };
const fail = (m) => { fails++; console.log('  FAIL ' + m); };

console.log('== Pipeline health check ==');

// 1. State YAML
const state = R('PIPELINE_STATE.md');
const phase = (state.match(/^phase:\s*(\S+)/m) || [])[1] || 'UNKNOWN';
const PHASES = ['NOT_STARTED','DISCOVERY','ARCH_DESIGN','SPRINT_PLANNED','DEV_IN_PROGRESS','DEV_COMPLETE','BA_ARCH_CONFIRM','READY_FOR_QA','QA_IN_PROGRESS','DONE'];
PHASES.includes(phase) ? ok('phase valid: ' + phase) : fail('invalid phase: ' + phase);

// 2. Phase-artifact consistency
const need = (f, min, label) => {
  const c = R(f);
  if (c.length < min || c.includes('Generated by the pipeline. Do not author manually'))
    fail(label + ' missing/placeholder (' + f + ')');
  else ok(label + ' present (' + c.length + ' bytes)');
};
const idx = PHASES.indexOf(phase);
if (idx >= PHASES.indexOf('ARCH_DESIGN')) need('01-discovery/requirements-brief.md', 2000, 'requirements brief');
if (idx >= PHASES.indexOf('SPRINT_PLANNED')) need('01-discovery/technical-design.md', 5000, 'technical design');
if (idx >= PHASES.indexOf('DEV_IN_PROGRESS')) need('02-build/sprint-plan.md', 3000, 'sprint plan');

// 3. Review packets vs jira-log status lines
const packets = (fs.existsSync('02-build/review-notes') ? fs.readdirSync('02-build/review-notes') : [])
  .filter(f => /^VS-\d+-review\.md$/.test(f)).map(f => f.match(/VS-\d+/)[0]);
const jlog = R('02-build/jira-log.md');
packets.forEach(vs => {
  new RegExp('^- .*\\| ' + vs + ' \\|.*(In Review|Review|Done)', 'm').test(jlog)
    ? ok(vs + ' packet has jira-log status line')
    : warn(vs + ' has a review packet but NO status line in jira-log.md');
});
if (!packets.length && idx >= PHASES.indexOf('DEV_IN_PROGRESS')) warn('no review packets yet in DEV_IN_PROGRESS');

// 4. Citation integrity: D-### / A-### cited vs defined
const defined = new Set([...R('.claude/memory/decisions.md').matchAll(/^\| (D-\d+)/gm)].map(m => m[1]));
[...R('.claude/memory/assumptions.md').matchAll(/^\| (A-\d+)/gm)].forEach(m => defined.add(m[1]));
const cited = new Set();
const scan = ['01-discovery/technical-design.md', '02-build/sprint-plan.md', '02-build/jira-log.md',
  ...packets.map(v => '02-build/review-notes/' + v + '-review.md')];
scan.forEach(f => [...R(f).matchAll(/\b([DA]-\d{3})\b/g)].forEach(m => cited.add(m[1])));
const missing = [...cited].filter(x => !defined.has(x)).sort();
missing.length ? fail('cited but missing from .claude/memory/: ' + missing.join(' '))
               : ok('all ' + cited.size + ' cited D-/A- IDs exist in memory');

// 5. Log freshness
const newestUnder = (dirs) => { let n = { f: null, m: 0 };
  const walk = d => { let e; try { e = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
    e.forEach(x => { if (x.name === '.git' || x.name === 'node_modules') return;
      const p = path.join(d, x.name);
      if (x.isDirectory()) walk(p); else { try { const m = fs.statSync(p).mtimeMs; if (m > n.m) n = { f: p, m }; } catch {} } }); };
  dirs.forEach(walk); return n; };
const nw = newestUnder(['01-discovery', '02-build', '03-qa', '04-confirmations', 'force-app']);
let logM = 0; try { logM = fs.statSync('.claude/logs/agent-runs.log').mtimeMs; } catch {}
nw.m > logM + 90_000 ? fail('agent-runs.log stale vs ' + nw.f) : ok('agent-runs.log fresh');

// 6. No-Aadhaar scan over force-app + seed data
let hits = [];
const scanA = d => { let e; try { e = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
  e.forEach(x => { const p = path.join(d, x.name);
    if (x.isDirectory()) scanA(p);
    else if (/\.(xml|js|ts|cls|json|csv|html|css|apex)$/.test(x.name)) {
      const c = R(p).replace(/[ -]/g, '');
      if (/(?<!\d)\d{12}(?!\d)/.test(c)) hits.push(p);
    } }); };
['force-app', 'scripts/seed-data'].forEach(scanA);
hits.length ? fail('possible Aadhaar-like 12-digit values in: ' + hits.join(', ')) : ok('no Aadhaar-like values in source/seed data');

// 7. Counts
const count = (f, re) => (R(f).match(re) || []).length;
console.log('== Counts ==');
console.log('  REQs: ' + count('01-discovery/requirements-brief.md', /^\| REQ-/gm)
  + ' | OQs: ' + count('01-discovery/open-questions.md', /^\| OQ-/gm)
  + ' | tickets: ' + count('02-build/jira-log.md', /^\| VS-\d+ \|/gm)
  + ' | packets: ' + packets.length
  + ' | TCs: ' + count('03-qa/test-plan.md', /^\| TC-/gm)
  + ' | bugs: ' + (fs.existsSync('03-qa/bug-reports') ? fs.readdirSync('03-qa/bug-reports').filter(f => f.startsWith('BUG-')).length : 0)
  + ' | deploys: ' + count('02-build/deployments.md', /^\| 20/gm));
console.log('== Result: ' + (fails ? 'FAIL (' + fails + ' failures, ' + warns + ' warnings)' : 'OK (' + warns + ' warnings)') + ' ==');
process.exit(fails ? 1 : 0);
